### ISSUE TITLE
Search Issues page which uses postgresql's full text search - special query operators don't seem to work right

### ISSUE THREAD

**Issue by ctrager** [ctrager/budoco#1]
The "-" operator, to exclude, doesn't seem to be working.

**Comment by ghost** [comment]
Seems to work. 😄

**Comment by ctrager** [comment]
Search for "dog"

![Screenshot from 2020-12-05 16-28-33](https://user-images.githubusercontent.com/61188/101266704-22a5d180-3717-11eb-9fd3-0b574e910715.png)

Searching for dog, but *NOT* cat:
![Screenshot from 2020-12-05 16-31-37](https://user-images.githubusercontent.com/61188/101266724-64367c80-3717-11eb-8d12-ea598b97b0f1.png)

**Comment by ctrager** [comment]
@ivangrek  - I updated this issue showing how it doesn't work for me.  But it does work for you?!?!!  Could it be some sort of postgresql setting? I have no clue.

**Comment by ghost** [comment]
> @ivangrek - I updated this issue showing how it doesn't work for me. But it does work for you?!?!! Could it be some sort of postgresql setting? I have no clue.

I am using UTF8 encoding for db.

**Comment by ctrager** [comment]
I'm ignorant about encodings. I installed as shown in the readme and did nothing after that.  Should I do something?

**Comment by ghost** [comment]
create database budoco with encoding 'UTF8';

I needed all the symbols.

**Comment by ghost** [comment]
Did you apply last changes?

**Comment by ctrager** [comment]
I tried making the same edits in my master and my search still didn't work.  Now I'm reading github docs to figure out how I can pull down your pull request locally to try it locally before I merge it. My git/github skills are rusty (not that they were ever that solid).  Give me a few minutes.

**Comment by ghost** [comment]
As remote https://github.com/ivangrek/budoco.git
https://docs.github.com/en/free-pro-team@latest/github/using-git/adding-a-remote
