### ISSUE TITLE
Make the ability to control the issue page's layout with css easier

### ISSUE THREAD

**Issue by ctrager** [ctrager/budoco#10]
Underneath the "Details" textarea are up to 8 dropdowns: org, assigned to, and the 6 custom fields.  Right now they are laid out using actual <table> tags, in two columns.

What I would like is that the layout is completely controlled by css and that the user can override whatever we do in css using the custom css file feature of the app.

For the initial experience, new installation, I would like two columns
Left:
org
priority aka custom 2
[custom 3] hidden
category aka custom 4
[custom 5] hidden

right
assigned to
status aka custom 1

but I would like custom css to demo how to move things around between columns.

**Comment by ctrager** [comment]
@ivangrek - If you are interesed in more work, this is my top priority. My css positioning skills are really really bad. I do a lot of trial and error and I really don't have a grasp of the fundamentals.

**Comment by ghost** [comment]
Most likely, a table tag will not work as a basis.

**Comment by ctrager** [comment]
FOR SURE a table tag won't work.

**Comment by ghost** [comment]
I understand correctly, you want to change the order and arrangement of elements?

**Comment by ghost** [comment]
[element 1]   [element 5]
[element 2]   [element 6]
[element 3]   [element 7]
[element 4]   [element 8]

to

[element 8]   [element 4]
[element 7]   [element 3]
[element 6]   [element 2]
[element 5]   [element 1]

or some randomly.

**Comment by ctrager** [comment]
No, I want it to look like the way it looks now, or pretty close to it.  But I want that look controlled by css in budoco.css, not by a table tag in the .cshtml file.

And I want a demo of how to change to positing in custom_css_example.css

**Comment by ghost** [comment]
First we need to use reset.css and reset browser default styles.
Prepare the canvas so to speak.

```
*,
*::before,
*::after {
  box-sizing: border-box;
  margin: 0;
  padding: 0;
}
```

**Comment by ghost** [comment]
Using variables for the same values.
https://developer.mozilla.org/en-US/docs/Web/CSS/var()

**Comment by ctrager** [comment]
Feel free to do all the smart best practice stuff while also making it not too hard for me to review/accept the pull request. So hopefully only changes to budoco.css related to issue.cshtml, custom_css_example.css, and issue.cshtml.

**Comment by ghost** [comment]
👍

**Comment by ghost** [comment]
Didn't you consider this option?
https://getbootstrap.com/

**Comment by ctrager** [comment]
I'm not trying to redesign the whole site.
I'm not trying to make it work with mobile.
I just want to have a solution for that specific section of the issue page.

**Comment by ctrager** [comment]
fyi: https://budoco.net/About

**Comment by ghost** [comment]
:+1:

**Comment by ghost** [comment]
Made some improvements. Added variables. Please look at what else to look for? That would not block css.

**Comment by ghost** [comment]
Only this section?

![image](https://user-images.githubusercontent.com/3169265/101679155-99203780-3a67-11eb-80fa-ecb70b3530b2.png)

**Comment by ctrager** [comment]
This issue is only about the section below the Details textarea and above the button.  Just the dropdowns.  I want the css to control whether to display them in one column or two and what order.

**Comment by ctrager** [comment]
I think i found a solution

**Comment by ghost** [comment]
👍

**Comment by ctrager** [comment]
https://jsfiddle.net/ctrager/qLj1kcm7/32/

**Comment by ctrager** [comment]
That fiddle does exactly what I want.  I originally assigned this to you because like the postgres full text search, I was really stuck and frustrated. Now, though, I know exactly what to do. If you don't want to work on this, that's okay, or if you want to complete it, that's okay too.

**Comment by ctrager** [comment]
This would be more fun to work on: https://github.com/ctrager/budoco/issues/31
Want it?

**Comment by ghost** [comment]
I have an idea to use "display: flex;".
But not sure if this will cover all the options you want.

**Comment by ctrager** [comment]
I had already tried flex. This grid thing seems to work better.  What do you think about you stopping working on this one and working on #31 instead?

**Comment by ghost** [comment]
I will switch because I do not see the end goal.

**Comment by ctrager** [comment]
Done (using display: grid)

**Comment by ghost** [comment]
:+1:
