### ISSUE TITLE
when urls appear in description, details, or post text, turn them into clickable <a> tags.

### ISSUE THREAD

**Issue by ctrager** [ctrager/budoco#22]
This needs to happen on the client side, because we don't want to use dangerous @Html.Raw on server. See how Search.cshtml turns the postgresql start/end markers into <b> and </b> tags and follow that pattern.

For recognizing urls, but maybe we also want to recognize example.com, example.org, and even example.net, even though that works bad with my own "BugTracker.NET".

url parser
https://mathiasbynens.be/demo/url-regex
https://gist.github.com/dperini/729294
Copyright (c) 2010-2018 Diego Perini (http://www.iport.it)

**Comment by ghost** [comment]
I am doing with this issue.

**Comment by ghost** [comment]
Not all URLs seem to parse. (

**Comment by ghost** [comment]
localhost don't work

**Comment by ctrager** [comment]
You did post comments but not issue description and issue details

**Comment by ctrager** [comment]
let's see how github handles github.com, bugtracker.net, google.com....

**Comment by ctrager** [comment]
okay, they want https://google.com...

**Comment by ghost** [comment]
https://localhost
Not replaceable.

**Comment by ctrager** [comment]
https://google.com gets replaced in the p_text field but this issue is also for i_description and i_details.

**Comment by ghost** [comment]
![image](https://user-images.githubusercontent.com/3169265/101898955-aba88700-3bb5-11eb-8d0e-2116a93814f8.png)

**Comment by ghost** [comment]
We can't do this just using textarea.

**Comment by ctrager** [comment]
Oops, you're right. Sorry.  I'm rusty.
