### ISSUE TITLE
Issues, history posts, for changes to description and details, something better than [hover to view]

### ISSUE THREAD

**Issue by ctrager** [ctrager/budoco#31]
[hover to view] was a placeholder. Better would be [click to view] and then a modal pops up with the text.

Or, maybe delux, you click to bring up a side-by-side diff.

**Comment by ctrager** [comment]
@ivangrek  -  This might be a more fun thing to work on.  This is how it works now:
![Screenshot from 2020-12-09 14-19-07](https://user-images.githubusercontent.com/61188/101682651-86870d80-3a29-11eb-9321-b074a7748599.png)

**Comment by ctrager** [comment]
When you change description or details, you'll get a history post that's like this.  If you hover where it says "hover to view" you get what you see in the screenshot above. What I want is more [click to view] and then a nice display of the text.  Or, to be really cool, you could click to get a side-by-side diff of the before and after. 
Details changed from [hover to view] to [hover to view] by admin on 12/9/2020 8:35:47 AM  post #88

**Comment by ghost** [comment]
I see only tooltip.

![image](https://user-images.githubusercontent.com/3169265/101684680-77c34980-3a6f-11eb-93a3-f969253d6212.png)

**Comment by ghost** [comment]
Do you want to show a modal on click?

**Comment by ghost** [comment]
Will it be correct?

Details changed by admin on 09.12.2020 22:31:36 post#14 [click to view] 

Do you want to keep this message flow?

**Comment by ghost** [comment]
![image](https://user-images.githubusercontent.com/3169265/101688326-89f3b680-3a74-11eb-894a-7d334a39d528.png)

**Comment by ctrager** [comment]
Not sure I understand your question. The point of this issue is I want the user to be able to see what the text WAS in the past.
With the dropdowns, I can just say  changed form "A" to "B", because the names are short.
With details and description, there's too much text to display so I don't want to show it until the user asks. 
So, my title="before_val", that was a very quick and dirty way, but it's ugly and not very good.  I want it nicer.
Either, display the text in a nice modal window, or, even more exciting, display a side-by-side diff.

**Comment by ghost** [comment]
Ok. I do.

**Comment by ctrager** [comment]
I found this: https://github.com/rtfpessoa/diff2html
I have no experience with it, but it might be worth exploring.

**Comment by ghost** [comment]
![1](https://user-images.githubusercontent.com/3169265/101706341-8884b700-3a91-11eb-8ce7-39bd61887827.gif)

**Comment by ghost** [comment]
> I found this: https://github.com/rtfpessoa/diff2html

diff format needs

**Comment by ctrager** [comment]
Things to think about:
What is the size of your popup window?
What if there's just a small amount of text?  Do you resize the window small?
What if there's a huge amount of text? You need to set a max size and then show scrollbars.
When you think you are done, let me know.
So the idea of showing a side-by-side diff, that's not something you like? That's not something you can do?

**Comment by ghost** [comment]
> What is the size of your popup window?
What if there's just a small amount of text? Do you resize the window small?
What if there's a huge amount of text? You need to set a max size and then show scrollbars.

The height depends on the content.

> So the idea of showing a side-by-side diff, that's not something you like? That's not something you can do?

I like side-by-side diff, but it needs research to  use.

**Comment by ctrager** [comment]
Test with content that's taller than the height of the screen.

**Comment by ghost** [comment]
This style breaks the layout as it is very general. (`<div>`)

![image](https://user-images.githubusercontent.com/3169265/101709856-ebc61780-3a98-11eb-92c2-5d204a170955.png)

**Comment by ctrager** [comment]
It's a default.  margin: 0, that's a default too.  I picked a default that would result in me doing the least overriding.  margin: 0, that would be a default that I'd be overriding a lot.

**Comment by ctrager** [comment]
I'm not saying that my way is the best, but I am saying that whether the default is 0 or whether the default is 15, it would frequently need to be overriden.

**Comment by ghost** [comment]
> I'm not saying that my way is the best, but I am saying that whether the default is 0 or whether the default is 15, it would frequently need to be overriden.

Sorry. I have no control over how rude or inappropriate the phrases can be. (My phrases.)

**Comment by ctrager** [comment]
done

**Comment by ghost** [comment]
👍
