### ISSUE TITLE
In Create/Update issue page, that extra click needed to expand the dropdown is annoying. Help me?

### ISSUE THREAD

**Issue by ctrager** [ctrager/budoco#4]
This is something I could use help with. I'm going to look at jquery widgets.

**Comment by ghost** [comment]
Hi!
I will be glad to help. How will it work?

**Comment by ctrager** [comment]
oh, sorry, I should have closed this issue. Have you tried the app? You are the first person to even notice it. Why are you interested?

**Comment by ghost** [comment]
> Have you tried the app?

Yes. Looks better.

> Why are you interested?

For fun. I love to program.

**Comment by ctrager** [comment]
Can you take a look at this issue?
https://github.com/ctrager/budoco/issues/1

**Comment by ghost** [comment]
> Can you take a look at this issue?

Ok

I even tried to do something like this, but I didn't have enough enthusiasm. :)
https://bug-tracker.azurewebsites.net/

**Comment by ctrager** [comment]
omg! I'm honored!

I'm retired, the election was making me mentally ill, stuck at home because of the pandemic, and it's cold outside, so, that created the conditions that got me motivated to give it a try.  It's gone way easier than I thought. 

I'm curious what features that exist in the original BugTracker.NET but don't yet exist in this rewrite are most important to you?

**Comment by ghost** [comment]
😃 👍

**Comment by ghost** [comment]
> I'm curious what features that exist in the original BugTracker.NET but don't yet exist in this rewrite are most important to you?

I think logs and reporting.

**Comment by ctrager** [comment]
The app writes logs. They are pretty verbose. I still need the admin page for viewing the logs without going to the server.

Reporting, I'm open to that feature being added when the code settles down because it's something that doesn't interact much with the rest of the code.
