### ISSUE TITLE
column "rp_desc" does not exist

### ISSUE THREAD

**Issue by tcplomp** [ctrager/budoco#44]
Fresh install, dotnet run fails witht he following error:

>  at budoco.Program.Main(String[] args) in /home/plompt/budoco-master/Program.cs:line 56
>   Exception data:
>     Severity: ERROR
>     SqlState: 42703
>     MessageText: column "rp_desc" does not exist
>     File: tablecmds.c
>     Line: 3138
>     Routine: renameatt_internal
>

Fixed by running the following SQL:
>  BEGIN; update db_version set db_version = 4; COMMIT;

**Comment by ctrager** [comment]
Thanks, fixed
