### ISSUE TITLE
Port old BugTracker.NET's report feature to Budoco

### ISSUE THREAD

**Issue by ctrager** [ctrager/budoco#8]
@ivangrek  -  This is yours if you want to work on it.

**Comment by ghost** [comment]
Ok

**Comment by ghost** [comment]
Could you please assigned to me?

**Comment by ctrager** [comment]
heads up - the following tables/fields are gone: status, priority, project, category. 
replaced by custom_1, 2, 3, 4, 5, 6
custom fields 1, 2, 4 are configured to look like status, priority, category

**Comment by ghost** [comment]
:+1:
